[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y wget unzip",
    "wget -q https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip -O /tmp/protoc.zip",
    "unzip -o /tmp/protoc.zip -d /usr/local",
    "rm /tmp/protoc.zip",
    "protoc --version"
]
